eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/

zuul:
  routes:
    greeter-app:
      path: /**
      url: http://greeter-app.default

spring:
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:9411
