eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/

zuul:
  routes:
    frontend:
      path: /
      url: http://frontend.default.svc.cluster.local/
    keycloak:
      path: /keycloak/**
      url: http://keycloak.default:8080/

spring:
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:9411
