eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-svc.default.svc.cluster.local:8761/eureka/

zuul:
  routes:
    fallback:
      path: /**
      service-id: frontend
