eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery.default.svc.cluster.local:8761/eureka/

zuul:
  routes:
    fallback:
      path: /**
      service-id: frontend

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:9411
